# Exercise Set 6
This exercise set corresponds to the numpy exercises provided by 06 numpy.ipynb on GitHub.

## Exercise 1

In [1]:
import matplotlib.pyplot as plt
import numpy as np

simulated = [55,31,22,86,63,61,62,81,73]
observed = [51,29,23,89,58,58,59,84,73]
sim = np.array(simulated)
obs = np.array(observed)

### Calculating the mean error.
error = sim - obs
mean_error = np.mean(error)
print(f'The mean error is {mean_error:.2f}')

### Calculating the coefficient of determination
sim_mean = np.mean(sim)
obs_mean = np.mean(obs)
sim_diffs = sim - sim_mean
obs_diffs = obs - obs_mean
sim_diffs_squared = np.square(sim_diffs)
obs_diffs_squared = np.square(obs_diffs)
sim_stddev = np.sqrt((1/len(sim))*np.sum(sim_diffs_squared))
obs_stddev = np.sqrt((1/len(obs))*np.sum(obs_diffs_squared))
diffs = sim_diffs*obs_diffs
coeff_det = np.square((1/len(sim))*np.sum(diffs)/(sim_stddev*obs_stddev))
print(f'The coefficient of determination is {coeff_det:.3f}')

### Calculating the Nash Coefficient
NSE = 1 - ((np.sum(np.square(error)))/(np.sum(np.square(obs_diffs))))
print(f'The Nash coefficient is {NSE:.3f}')

The mean error is 1.11
The coefficient of determination is 0.984
The Nash coefficient is 0.979


## Exercise 2

In [16]:
import matplotlib.pyplot as plt
import numpy as np

def linear_regression(x,y):
    x = np.array(x)
    y = np.array(y)
    x_mean = np.mean(x)
    y_mean = np.mean(y)
    x_diff = x - x_mean
    y_diff = y - y_mean
    SSx = np.sum(np.square(x_diff))
    SSy = np.sum(np.square(y_diff))
    SSxy = np.sum(x_diff*y_diff)
    c = y_mean - ((SSx/SSxy)*x_mean)
    a = SSxy/SSx
    ssqe = SSy - a*SSxy
    return a,c,ssqe

simulated = [55,31,22,86,63,61,62,81,73]
observed = [51,29,23,89,58,58,59,84,73]
linear_regression(observed,simulated)

(0.9443823677300406, -2.317777712045178, 58.585032683391546)

## Exercise 3

In [20]:
import matplotlib.pyplot as plt
import numpy as np

landuse = np.random.randint(1, 5, [5, 5])
precip  = np.random.random([5, 5])

print('landuse\n', landuse)
print('precip \n', precip)

landuse_types = np.unique(landuse)
avg_precip_usetype = np.zeros([len(landuse_types)])
for i in range(len(landuse_types)):
    precip_usetype = precip[landuse == landuse_types[i]]
    avg_precip_usetype[i] = np.mean(precip_usetype)
    print(f'The average precipitation for land use type {landuse_types[i]} is {avg_precip_usetype[i]:.2f} inches.')



landuse
 [[3 2 1 3 3]
 [4 4 3 2 2]
 [1 4 4 4 4]
 [4 4 2 3 3]
 [2 4 3 4 3]]
precip 
 [[0.90174689 0.96481514 0.67059595 0.97434665 0.64928633]
 [0.07149246 0.79133547 0.57059913 0.03729607 0.34166356]
 [0.01447465 0.4700988  0.5567051  0.8899186  0.86577559]
 [0.91658436 0.36589098 0.86417662 0.18152204 0.17726156]
 [0.59433059 0.38811159 0.81589748 0.80212363 0.59427104]]
The average precipitation for land use type 1 is 0.34 inches.
The average precipitation for land use type 2 is 0.56 inches.
The average precipitation for land use type 3 is 0.61 inches.
The average precipitation for land use type 4 is 0.61 inches.


## Exercise 4

In [21]:
import matplotlib.pyplot as plt
import numpy as np

landuse = np.random.randint(0,2,[6,6])
#landuse = np.random.randint(0, 1, [6, 6])
precip  = np.random.random([6, 6])

print('landuse\n', landuse)
print('precip \n', precip)

def bufferzones(landuse,buffer):
    irr_indices = np.where(landuse == 1)
    for i in range(len(irr_indices[0])):
        row = irr_indices[0][i]
        col = irr_indices[1][i]
        lower_rowbound = row - buffer
        upper_rowbound = row + buffer
        lower_colbound = col - buffer
        upper_colbound = col + buffer
        if lower_rowbound < 0:
            lower_rowbound = 0
        if upper_rowbound > len(landuse) + 1:
            upper_rowbound = len(landuse) + 1
        if lower_colbound < 0:
            lower_colbound = 0
        if upper_colbound > landuse.shape[1]:
            upper_colbound = landuse.shape[1] + 1
        extraction = landuse[lower_rowbound:upper_rowbound+1][lower_colbound:upper_colbound+1]
        extraction[extraction != 1] = 2
        landuse[lower_rowbound:upper_rowbound+1][lower_colbound:upper_colbound+1] = extraction
    landuse_buffered = landuse
    return landuse_buffered

landuse_buffered = bufferzones(landuse,1)
print(landuse_buffered)
mean_precip1 = np.mean(precip[landuse_buffered == 2])
print(f'The average precipitation in the buffered region around the irrigated areas is {mean_precip1:.2f}.')

landuse
 [[1 1 1 1 0 1]
 [0 0 0 0 0 1]
 [0 1 1 1 1 1]
 [0 0 1 1 0 0]
 [0 1 0 1 0 0]
 [0 1 0 1 0 1]]
precip 
 [[0.96932066 0.25875787 0.80011724 0.53490778 0.7983298  0.55775873]
 [0.09231181 0.49349008 0.29328782 0.45140232 0.60825706 0.76006699]
 [0.10947631 0.91750643 0.79679411 0.09166039 0.06736005 0.74605915]
 [0.50682529 0.1682477  0.50776528 0.80147912 0.68113728 0.57919153]
 [0.47328601 0.22138341 0.27222982 0.55014675 0.29971439 0.43586762]
 [0.98823655 0.75520248 0.43923412 0.22592703 0.67370577 0.94751432]]
[[1 1 1 1 2 1]
 [2 2 2 2 2 1]
 [2 1 1 1 1 1]
 [2 2 1 1 2 2]
 [2 1 2 1 2 2]
 [2 1 2 1 2 1]]
The average precipitation in the buffered region around the irrigated areas is 0.46


## Exercise 5

In [32]:
def distmatrix(points):
    points = np.array(points)
    x1 = points[:,0]
    x2 = np.reshape(points[:,0],(len(points[:,0]),1))
    diff_x = x2 - x1
    y1 = points[:,1]
    y2 = np.reshape(points[:,1],(len(points[:,1]),1))
    diff_y = y2 - y1
    dist = np.sqrt(np.square(diff_x) + np.square(diff_y))
    return print(dist)

points = [(3, 4), (1, 2), (7, 8), (9, 4), (6, 5), (8, 7), (4, 7)]
distmatrix(points)

[[0.         2.82842712 5.65685425 6.         3.16227766 5.83095189
  3.16227766]
 [2.82842712 0.         8.48528137 8.24621125 5.83095189 8.60232527
  5.83095189]
 [5.65685425 8.48528137 0.         4.47213595 3.16227766 1.41421356
  3.16227766]
 [6.         8.24621125 4.47213595 0.         3.16227766 3.16227766
  5.83095189]
 [3.16227766 5.83095189 3.16227766 3.16227766 0.         2.82842712
  2.82842712]
 [5.83095189 8.60232527 1.41421356 3.16227766 2.82842712 0.
  4.        ]
 [3.16227766 5.83095189 3.16227766 5.83095189 2.82842712 4.
  0.        ]]
